version: '3'
services:
  module1:
    image: localhost:5000/junkward-app-internal-api:latest
    ports:
      - "38080:38080"
    environment:
      - spring.profiles.active=dev

  frontend:
    image: localhost:5000/junkyard-frontend:latest
    ports:
      - "30000:3000"
    environment:
      BACKEND_API_URL: http://module1:38080/v1/api
